import type { ClassificationRule, StyleRule } from "@/lib/business/understanding/types";

export const CLASSIFICATION_RULES: ClassificationRule[] = [
  // Beauty
  {
    id: "beauty-core",
    vertical: "beauty",
    keywords: [
      "beauty",
      "skincare",
      "skin care",
      "makeup",
      "cosmetic",
      "cosmetics",
      "serum",
      "moisturizer",
      "retinol",
      "cleanser",
      "toner",
      "lipstick",
      "foundation",
      "mascara",
      "haircare",
      "shampoo",
      "bodycare",
      "clean beauty",
      "زیبایی",
      "پوست",
      "آرایش",
      "سرم",
      "کرم",
      "مو",
    ],
    categories: ["beauty", "skincare", "makeup", "cosmetics", "زیبایی"],
    attributes: ["skinType", "concerns", "ingredients", "routineStep"],
    weight: 1,
  },
  {
    id: "beauty-skincare",
    vertical: "beauty",
    subVertical: "skincare",
    keywords: ["skincare", "serum", "moisturizer", "retinol", "acne", "barrier", "مراقبت پوست"],
    weight: 1.2,
  },
  {
    id: "beauty-makeup",
    vertical: "beauty",
    subVertical: "makeup",
    keywords: ["makeup", "lipstick", "foundation", "mascara", "آرایش"],
    weight: 1.2,
  },
  {
    id: "beauty-haircare",
    vertical: "beauty",
    subVertical: "haircare",
    keywords: ["haircare", "shampoo", "conditioner", "hair oil", "مراقبت مو"],
    weight: 1.2,
  },
  {
    id: "beauty-bodycare",
    vertical: "beauty",
    subVertical: "bodycare",
    keywords: ["bodycare", "body oil", "body lotion", "مراقبت بدن"],
    weight: 1.2,
  },

  // Fashion
  {
    id: "fashion-core",
    vertical: "fashion",
    keywords: [
      "fashion",
      "clothing",
      "apparel",
      "dress",
      "wear",
      "lookbook",
      "collection",
      "designer",
      "streetwear",
      "outfit",
      "jacket",
      "pants",
      "مد",
      "پوشاک",
      "لباس",
      "استایل",
    ],
    categories: ["fashion", "clothing", "apparel", "مد", "پوشاک"],
    attributes: ["size", "fit", "material", "color", "occasion"],
    weight: 1,
  },
  {
    id: "fashion-women",
    vertical: "fashion",
    subVertical: "women",
    keywords: ["women", "womenswear", "زنانه"],
    weight: 1.1,
  },
  {
    id: "fashion-men",
    vertical: "fashion",
    subVertical: "men",
    keywords: ["men", "menswear", "مردانه"],
    weight: 1.1,
  },
  {
    id: "fashion-accessories",
    vertical: "fashion",
    subVertical: "accessories",
    keywords: ["accessories", "bag", "belt", "اکسسوری"],
    weight: 1.1,
  },

  // Jewelry
  {
    id: "jewelry-core",
    vertical: "jewelry",
    keywords: [
      "jewelry",
      "jewellery",
      "ring",
      "necklace",
      "bracelet",
      "earring",
      "earrings",
      "gold",
      "silver",
      "diamond",
      "جواهر",
      "انگشتر",
      "گردنبند",
      "گوشواره",
      "طلا",
      "نقره",
    ],
    categories: ["jewelry", "jewellery", "جواهرات"],
    attributes: ["material", "metal", "stone", "occasion"],
    weight: 1,
  },
  {
    id: "jewelry-rings",
    vertical: "jewelry",
    subVertical: "rings",
    keywords: ["ring", "rings", "انگشتر"],
    weight: 1.15,
  },
  {
    id: "jewelry-necklaces",
    vertical: "jewelry",
    subVertical: "necklaces",
    keywords: ["necklace", "pendant", "گردنبند"],
    weight: 1.15,
  },

  // Coffee
  {
    id: "coffee-core",
    vertical: "coffee",
    keywords: [
      "coffee",
      "roastery",
      "roaster",
      "espresso",
      "brew",
      "beans",
      "bean",
      "origin",
      "roast",
      "specialty coffee",
      "قهوه",
      "رست",
      "اسپرسو",
      "دانه",
    ],
    categories: ["coffee", "cafe", "roastery", "قهوه"],
    attributes: ["origin", "roastLevel", "flavorNotes", "process", "brewMethod"],
    weight: 1,
  },
  {
    id: "coffee-beans",
    vertical: "coffee",
    subVertical: "beans",
    keywords: ["beans", "whole bean", "دانه"],
    weight: 1.15,
  },
  {
    id: "coffee-roastery",
    vertical: "coffee",
    subVertical: "roastery",
    keywords: ["roastery", "roaster", "رستری"],
    weight: 1.15,
  },
  {
    id: "coffee-subscription",
    vertical: "coffee",
    subVertical: "subscription",
    keywords: ["subscription", "subscribe", "اشتراک"],
    weight: 1.1,
  },

  // Furniture
  {
    id: "furniture-core",
    vertical: "furniture",
    keywords: [
      "furniture",
      "sofa",
      "chair",
      "table",
      "interior",
      "home furniture",
      "wood",
      "cabinet",
      "desk",
      "مبلمان",
      "مبل",
      "صندلی",
      "میز",
      "دکوراسیون",
    ],
    categories: ["furniture", "home", "interior", "مبلمان"],
    attributes: ["room", "material", "dimensions", "designer"],
    weight: 1,
  },
  {
    id: "furniture-living",
    vertical: "furniture",
    subVertical: "living",
    keywords: ["living", "sofa", "نشیمن"],
    weight: 1.1,
  },
  {
    id: "furniture-office",
    vertical: "furniture",
    subVertical: "office",
    keywords: ["office", "desk", "اداری"],
    weight: 1.1,
  },
];

export const STYLE_RULES: StyleRule[] = [
  {
    id: "style-minimal",
    style: "minimal",
    mood: "minimal",
    keywords: ["minimal", "clean", "simple", "مینیمال"],
    weight: 1,
  },
  {
    id: "style-editorial",
    style: "editorial",
    mood: "editorial",
    keywords: ["editorial", "magazine", "story", "ادیتوریال"],
    weight: 1,
  },
  {
    id: "style-luxury",
    style: "luxury",
    mood: "luxury",
    keywords: ["luxury", "premium", "elegant", "لوکس"],
    weight: 1,
  },
  {
    id: "style-natural",
    style: "natural",
    mood: "natural",
    keywords: ["natural", "organic", "warm", "طبیعی"],
    weight: 1,
  },
  {
    id: "style-modern",
    style: "modern",
    mood: "modern",
    keywords: ["modern", "contemporary", "مدرن"],
    weight: 1,
  },
  {
    id: "style-bold",
    style: "bold",
    mood: "bold",
    keywords: ["bold", "statement", "vibrant", "جسور"],
    weight: 1,
  },
];
