import type { TemplateRecipe } from "@/lib/store/recipes/types";

export const CORE_TEMPLATE_RECIPES: TemplateRecipe[] = [
  {
    id: "beauty-editorial",
    vertical: "beauty",
    label: { fa: "بیوتی ادیتوریال", en: "Beauty editorial" },
    mood: "natural",
    baseTemplate: "store",
    recommended: true,
    sections: [
      { type: "hero", variant: "overlay" },
      { type: "categories" },
      { type: "featured-products" },
      { type: "bestsellers" },
      { type: "product-spotlight" },
      { type: "gallery" },
      { type: "about" },
      { type: "faq" },
      { type: "cta" },
      { type: "footer" },
    ],
  },
  {
    id: "beauty-commerce",
    vertical: "beauty",
    label: { fa: "بیوتی فروشگاهی", en: "Beauty commerce" },
    mood: "modern",
    baseTemplate: "store",
    sections: [
      { type: "hero", variant: "split" },
      { type: "products" },
      { type: "categories" },
      { type: "bestsellers" },
      { type: "promo" },
      { type: "faq" },
      { type: "contact" },
      { type: "footer" },
    ],
  },
  {
    id: "fashion-editorial",
    vertical: "fashion",
    label: { fa: "فشن ادیتوریال", en: "Fashion editorial" },
    mood: "editorial",
    baseTemplate: "store",
    recommended: true,
    sections: [
      { type: "hero", variant: "editorial" },
      { type: "gallery" },
      { type: "featured-products" },
      { type: "categories" },
      { type: "bestsellers" },
      { type: "products" },
      { type: "about" },
      { type: "cta" },
      { type: "footer" },
    ],
  },
  {
    id: "fashion-commerce",
    vertical: "fashion",
    label: { fa: "فشن فروشگاهی", en: "Fashion commerce" },
    mood: "bold",
    baseTemplate: "store",
    sections: [
      { type: "hero", variant: "minimal" },
      { type: "categories" },
      { type: "products" },
      { type: "featured-products" },
      { type: "gallery" },
      { type: "promo" },
      { type: "footer" },
    ],
  },
  {
    id: "jewelry-editorial",
    vertical: "jewelry",
    label: { fa: "جواهرات ادیتوریال", en: "Jewelry editorial" },
    mood: "luxury",
    baseTemplate: "store",
    recommended: true,
    sections: [
      { type: "hero", variant: "overlay" },
      { type: "featured-products" },
      { type: "product-spotlight" },
      { type: "categories" },
      { type: "gallery" },
      { type: "products" },
      { type: "about" },
      { type: "faq" },
      { type: "footer" },
    ],
  },
  {
    id: "coffee-story",
    vertical: "coffee",
    label: { fa: "داستان قهوه", en: "Coffee story" },
    mood: "natural",
    baseTemplate: "store",
    recommended: true,
    sections: [
      { type: "hero", variant: "editorial" },
      { type: "about" },
      { type: "featured-products" },
      { type: "products" },
      { type: "bestsellers" },
      { type: "gallery" },
      { type: "faq" },
      { type: "cta" },
      { type: "footer" },
    ],
  },
  {
    id: "coffee-commerce",
    vertical: "coffee",
    label: { fa: "قهوه فروشگاهی", en: "Coffee commerce" },
    mood: "minimal",
    baseTemplate: "store",
    sections: [
      { type: "hero", variant: "split" },
      { type: "products" },
      { type: "bestsellers" },
      { type: "categories" },
      { type: "promo" },
      { type: "contact" },
      { type: "footer" },
    ],
  },
  {
    id: "furniture-editorial",
    vertical: "furniture",
    label: { fa: "مبلمان ادیتوریال", en: "Furniture editorial" },
    mood: "minimal",
    baseTemplate: "store",
    recommended: true,
    sections: [
      { type: "hero", variant: "overlay" },
      { type: "categories" },
      { type: "featured-products" },
      { type: "product-spotlight" },
      { type: "gallery" },
      { type: "products" },
      { type: "about" },
      { type: "faq" },
      { type: "footer" },
    ],
  },
  {
    id: "generic-store",
    vertical: "generic",
    label: { fa: "فروشگاه عمومی", en: "Generic store" },
    mood: "modern",
    baseTemplate: "store",
    recommended: true,
    sections: [
      { type: "hero" },
      { type: "categories" },
      { type: "featured-products" },
      { type: "products" },
      { type: "bestsellers" },
      { type: "about" },
      { type: "gallery" },
      { type: "faq" },
      { type: "contact" },
      { type: "cta" },
      { type: "footer" },
    ],
  },
];
