import type { TemplateRecipe } from "@/lib/store/recipes/types";

export const CORE_TEMPLATE_RECIPES: TemplateRecipe[] = [
  {
    id: "beauty-editorial",
    vertical: "beauty",
    label: { fa: "بیوتی ادیتوریال", en: "Beauty editorial" },
    mood: "natural",
    baseTemplate: "store",
    recommended: true,
    sections: [
      { type: "hero", variant: "fan" },
      { type: "shop-by-concern" },
      { type: "featured-products" },
      { type: "routine" },
      { type: "ingredient-story" },
      { type: "bestsellers" },
      { type: "product-finder" },
      { type: "gallery" },
      { type: "cta" },
      { type: "footer" },
    ],
  },
  {
    id: "beauty-commerce",
    vertical: "beauty",
    label: { fa: "بیوتی فروشگاهی", en: "Beauty commerce" },
    mood: "modern",
    baseTemplate: "store",
    sections: [
      { type: "hero", variant: "split" },
      { type: "shop-by-skin-type" },
      { type: "products" },
      { type: "bestsellers" },
      { type: "routine" },
      { type: "promo" },
      { type: "faq" },
      { type: "footer" },
    ],
  },
  {
    id: "fashion-editorial",
    vertical: "fashion",
    label: { fa: "فشن ادیتوریال", en: "Fashion editorial" },
    mood: "editorial",
    baseTemplate: "store",
    recommended: true,
    sections: [
      { type: "hero", variant: "editorial" },
      { type: "lookbook" },
      { type: "collection-story" },
      { type: "featured-products" },
      { type: "shop-the-look" },
      { type: "categories" },
      { type: "style-guide" },
      { type: "cta" },
      { type: "footer" },
    ],
  },
  {
    id: "fashion-commerce",
    vertical: "fashion",
    label: { fa: "فشن فروشگاهی", en: "Fashion commerce" },
    mood: "bold",
    baseTemplate: "store",
    sections: [
      { type: "hero", variant: "minimal" },
      { type: "categories" },
      { type: "products" },
      { type: "fit-guide" },
      { type: "lookbook" },
      { type: "promo" },
      { type: "footer" },
    ],
  },
  {
    id: "jewelry-editorial",
    vertical: "jewelry",
    label: { fa: "جواهرات ادیتوریال", en: "Jewelry editorial" },
    mood: "luxury",
    baseTemplate: "store",
    recommended: true,
    sections: [
      { type: "hero", variant: "fan" },
      { type: "shop-by-material" },
      { type: "featured-products" },
      { type: "collection-story" },
      { type: "product-spotlight" },
      { type: "stack-builder" },
      { type: "shop-by-occasion" },
      { type: "jewelry-care" },
      { type: "footer" },
    ],
  },
  {
    id: "coffee-story",
    vertical: "coffee",
    label: { fa: "داستان قهوه", en: "Coffee story" },
    mood: "natural",
    baseTemplate: "store",
    recommended: true,
    sections: [
      { type: "hero", variant: "editorial" },
      { type: "roaster-story" },
      { type: "origin-explorer" },
      { type: "featured-products" },
      { type: "flavor-profile" },
      { type: "brew-guide" },
      { type: "products" },
      { type: "subscription" },
      { type: "cta" },
      { type: "footer" },
    ],
  },
  {
    id: "coffee-commerce",
    vertical: "coffee",
    label: { fa: "قهوه فروشگاهی", en: "Coffee commerce" },
    mood: "minimal",
    baseTemplate: "store",
    sections: [
      { type: "hero", variant: "split" },
      { type: "coffee-finder" },
      { type: "products" },
      { type: "bestsellers" },
      { type: "brew-guide" },
      { type: "subscription" },
      { type: "footer" },
    ],
  },
  {
    id: "furniture-editorial",
    vertical: "furniture",
    label: { fa: "مبلمان ادیتوریال", en: "Furniture editorial" },
    mood: "minimal",
    baseTemplate: "store",
    recommended: true,
    sections: [
      { type: "hero", variant: "fan" },
      { type: "shop-by-room" },
      { type: "room-inspiration" },
      { type: "featured-products" },
      { type: "materials" },
      { type: "product-spotlight" },
      { type: "projects" },
      { type: "dimensions" },
      { type: "footer" },
    ],
  },
  {
    id: "generic-store",
    vertical: "generic",
    label: { fa: "فروشگاه عمومی", en: "Generic store" },
    mood: "modern",
    baseTemplate: "store",
    recommended: true,
    sections: [
      { type: "hero" },
      { type: "categories" },
      { type: "featured-products" },
      { type: "products" },
      { type: "bestsellers" },
      { type: "about" },
      { type: "gallery" },
      { type: "faq" },
      { type: "contact" },
      { type: "cta" },
      { type: "footer" },
    ],
  },
];
