import type { CSSProperties } from "react";
import type { StoreTokens } from "@/lib/store/theme";
import {
  primitiveLayout,
  primitiveMotion,
  primitiveShadow,
  primitiveSpace,
} from "@/lib/design-system/primitives";
import { imageAspect } from "@/lib/design-system/foundation";

/**
 * Maps semantic StoreTokens → existing `--store-*` CSS variables.
 * Keeps app/store.css and all consumers backward-compatible.
 */
export function storeCssVars(tokens: StoreTokens): CSSProperties {
  return {
    ["--store-bg" as string]: tokens.background,
    ["--store-bg-subtle" as string]: tokens.backgroundSubtle,
    ["--store-surface" as string]: tokens.surface,
    ["--store-surface-elevated" as string]: tokens.surfaceElevated,
    ["--store-fg" as string]: tokens.foreground,
    ["--store-fg-secondary" as string]: tokens.foregroundSecondary,
    ["--store-fg-muted" as string]: tokens.foregroundMuted,
    ["--store-border" as string]: tokens.border,
    ["--store-border-subtle" as string]: tokens.borderSubtle,
    ["--store-border-strong" as string]: tokens.borderStrong,
    ["--store-accent" as string]: tokens.accent,
    ["--store-accent-fg" as string]: tokens.accentForeground,
    ["--store-primary" as string]: tokens.accent,
    ["--store-primary-fg" as string]: tokens.accentForeground,
    ["--store-secondary" as string]: tokens.foreground,
    ["--store-secondary-fg" as string]: tokens.background,
    ["--store-destructive" as string]: tokens.error,
    ["--store-success" as string]: tokens.success,
    ["--store-warning" as string]: tokens.warning,
    ["--store-error" as string]: tokens.error,
    ["--store-muted" as string]: tokens.backgroundSubtle,
    ["--store-muted-fg" as string]: tokens.foregroundMuted,
    ["--store-surface-muted" as string]: tokens.backgroundSubtle,
    ["--store-surface-hover" as string]: tokens.surfaceElevated,
    ["--store-wrap" as string]: primitiveLayout.pageMax,
    ["--store-space-1" as string]: primitiveSpace[1],
    ["--store-space-2" as string]: primitiveSpace[2],
    ["--store-space-3" as string]: primitiveSpace[3],
    ["--store-space-4" as string]: primitiveSpace[4],
    ["--store-space-5" as string]: primitiveSpace[5],
    ["--store-space-6" as string]: primitiveSpace[6],
    ["--store-space-8" as string]: primitiveSpace[8],
    ["--store-space-10" as string]: primitiveSpace[10],
    ["--store-space-12" as string]: primitiveSpace[12],
    ["--store-space-16" as string]: primitiveSpace[16],
    ["--store-space-20" as string]: primitiveSpace[20],
    ["--store-space-24" as string]: primitiveSpace[24],
    ["--store-space-30" as string]: primitiveSpace[30],
    ["--store-space-40" as string]: primitiveSpace[40],
    ["--store-section-pad" as string]: tokens.sectionPad,
    ["--store-radius-none" as string]: "0",
    ["--store-radius-sm" as string]: tokens.radiusSm,
    ["--store-radius-md" as string]: tokens.radiusMd,
    ["--store-radius-lg" as string]: tokens.radiusLg,
    ["--store-radius-xl" as string]: tokens.radiusXl,
    ["--store-radius-full" as string]: "9999px",
    ["--store-btn-radius" as string]: tokens.buttonRadius,
    ["--store-ratio" as string]: imageAspect.portrait,
    ["--store-shadow-subtle" as string]: primitiveShadow.subtle,
    ["--store-shadow-card" as string]: primitiveShadow.card,
    ["--store-shadow-elevated" as string]: primitiveShadow.elevated,
    ["--store-shadow-overlay" as string]: primitiveShadow.overlay,
    ["--store-ease" as string]: primitiveMotion.ease,
    ["--store-ease-out" as string]: primitiveMotion.easeOut,
    ["--store-ease-in-out" as string]: primitiveMotion.easeInOut,
    ["--store-dur-fast" as string]: primitiveMotion.durationFast,
    ["--store-dur" as string]: primitiveMotion.duration,
    ["--store-dur-slow" as string]: primitiveMotion.durationSlow,
    background: tokens.background,
    color: tokens.foreground,
  };
}
